### ISSUE TITLE
actions-rs/toolchainからdtolnay/rust-toolchainに切り替える

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#312]
## 内容

VOICEVOX/voicevox#987 関連です。

このリポジトリで使っている[actions-rs/toolchain](https://github.com/actions-rs/install)はメンテナンスが放棄されており、今後メンテナの加入による再開も望めない状態です。

移行先として[dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain)を提案します。実装の中身はNodeではなく[数十行程度の簡潔なBash](https://github.com/dtolnay/rust-toolchain/blob/master/action.yml)なので何をやっているかはすぐにわかると思います。

[rust-toolchain(.toml)へのサポートはしないことを表明している](https://github.com/dtolnay/rust-toolchain/issues/12)ため、このリポジトリにおいては1step分膨らみますがそれ以外の問題はないかと。

```yaml
      - id: cat-rust-toolchain
        shell: bash
        run: echo "::set-output name=toolchain::$(cat ./rust-toolchain)"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.cat-rust-toolchain.toolchain }}
          targets: ${{ matrix.target }}
```

開発者がdtolnay氏なのでdtolnay/rust-toolchainの将来性についても問題無いかと。何よりもsynとかの色んなライブラリでドッグフーディングされていることが大きいです。

## OSの種類/ディストリ/バージョン

全部

## その他

Q. dtolnay氏とは誰か?

Rust本体のみならず数々の有名/重要ライブラリを作っている人で、synとかanyhowとかの作者です。

- [去年行われたとあるアンケートの第一問目](https://www.guidedtrack.com/programs/kfqw8vs/run?utm_source=pocket_mylist)
- [「Rustでやると知らないうちに詰む設計」を避けるためのTipsを集めてみる](https://zenn.dev/qnighy/scraps/93071f7c813cb9)
    > Rustも色々闇テクニックはあるので出来ないとも限らないが、だいたいメタプログラミングっぽい話で **[dtolnayが](https://github.com/dtolnay?tab=repositories)[やって](https://github.com/dtolnay/case-studies)ないことはできない** と思ってよさそう。
